### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by dattran2346** [ledaian41/wtodo#1]
### Thank you for your submission
- 20h!! You really pushed effort on doing the prework, I really appreciate that
- How you have learnt Android? I just wondering?

### Good Stuff
- Using custom `ArrayAdapter` with `ListView`
- Implement persistent database using `SQLOpenHelper` and `ContentValues`

### Suggesstions

- Try yourself with `RecyclerView` and `RecyclerAdapter`, they are very similar to `ListView` and `ArrayAdapter`
- Instead of using `putExtra("item")`, you can extract the `item` string into `public final String ITEM = "item"` constant, I have seen people make bugs because they mistype the word
- Try [ButterKnife](http://jakewharton.github.io/butterknife/), this is a very easy to use library to reduce `findViewById()` boilerplate code, they also support `onClick()` very nicely
- Instead of using `Save` and `Cancel` button, try using `ItemMenu` and `Toolbar` instead, that will look definitely better
- Try to tweak UI more, the UI is better than the naive implementation in the tutorial, however it doen't look nice enough

**Comment by ledaian41** [comment]
Thanks for your suggestion, @dattran2346 
I'm trying improve my prework. I'm a beginner in Android, I have learned from many toturials online. There are few issues that I'm not fully understood.

**Comment by dattran2346** [comment]
@ledaian41 What issue are you not really understood? Perhaps I can help you?
Ps: Sorry for late reply to you 😭

**Comment by ledaian41** [comment]
@dattran2346 
- It's about RecyclerView, how can I handle onItemClick event and get item's position? In ListView, I have handled onItemClick event easily but in RecyclerView, I could not found onItemClickListener. :(
- About Context, does every activity have a context ? and can I call or use a context in an other activity ? While searching for ViewHolder, I found that can get context from parameter ViewGroup. 
Many thanks,

**Comment by dattran2346** [comment]
@ledaian41 

- You can do this in `RecyclerViewAdapter`:

```java
@Override
public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
   holder.itemView.setOnClickListener(v -> {
            
   }); 	  
}
    
```

- `Activity` is the subclass of `Context`; but `View` has `Context`, you can see that in View construction. People usually pass the activity via RecyclerAdapter **construction**, the **ViewGroup** is actually the RecyclerView where the Adapter attach to. Because **ViewGroup** is also a **View**, so you can also use Context from ViewGroup. Choose whatever you favor.

Ps: Does that make sense to you?

**Comment by ledaian41** [comment]
@dattran2346 
Thank you, I have understood about Context and have handled onItemClick event in RecyclerViewAdapter.
Many thanks,
